baseurl = "https://sakeven.github.io/"
languageCode = "en-us"
title = "Sakeven's Blog"
theme = "xmin"
hasCJKLanguage = true
enableEmoji = true


[permalinks]
    posts = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    footer = "&copy; [Sakven Jiang](mailto:sakeven.jiang@gmail.com) 2017-2019 | [GitHub](https://github.com/sakeven)"
